[2025-05-05 12:03:28,300] 97 werkzeug - WARNING -  * Debugger is active!
[2025-05-05 12:03:28,304] 97 werkzeug - INFO -  * Debugger PIN: 143-783-530
[2025-05-05 12:06:02,531] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 12:06:02] "GET / HTTP/1.1" 200 -
[2025-05-05 12:06:02,619] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 12:06:02] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-05-05 12:06:26,301] 34 root - INFO - Received form data:
[2025-05-05 12:06:26,303] 37 root - INFO - Location: washington
[2025-05-05 12:06:26,303] 37 root - INFO - Temperature: 23
[2025-05-05 12:06:26,303] 37 root - INFO - Humidity: 34
[2025-05-05 12:06:26,304] 37 root - INFO - Wind_Speed: 50
[2025-05-05 12:06:26,304] 37 root - INFO - Precipitation: 23
[2025-05-05 12:06:26,304] 37 root - INFO - Cloud_Cover: overcast
[2025-05-05 12:06:26,304] 59 root - INFO - Input data validated and created
[2025-05-05 12:06:26,304] 62 root - INFO - Dataframe Gathered
[2025-05-05 12:06:26,304] 63 root - INFO - Input DataFrame created:
[2025-05-05 12:06:26,311] 64 root - INFO - 
     Location  Temperature  Humidity  Wind_Speed  Precipitation Cloud_Cover
0  washington         23.0      34.0        50.0           23.0    overcast
[2025-05-05 12:06:26,311] 67 root - INFO - Initializing PredictPipeline...
[2025-05-05 12:06:26,311] 69 root - INFO - Making prediction...
[2025-05-05 12:06:26,311] 53 root - INFO - Exception Occured in load_object function utils
[2025-05-05 12:06:26,313] 81 root - ERROR - Prediction error: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]
Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py", line 50, in load_object
    with open(file_path,'rb') as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 18, in predict
    preprocessor=load_object(preprocessor_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py", line 54, in load_object
    raise customexception(e,sys)
src.Weather_prediction.exception.customexception: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py", line 72, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 30, in predict
    raise customexception(e,sys)
src.Weather_prediction.exception.customexception: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]
[2025-05-05 12:06:26,315] 90 root - ERROR - Error in predict_datapoint: An error occurred: Prediction failed: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]

Traceback:
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py", line 72, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 30, in predict
    raise customexception(e,sys)
Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py", line 50, in load_object
    with open(file_path,'rb') as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 18, in predict
    preprocessor=load_object(preprocessor_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py", line 54, in load_object
    raise customexception(e,sys)
src.Weather_prediction.exception.customexception: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py", line 72, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 30, in predict
    raise customexception(e,sys)
src.Weather_prediction.exception.customexception: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py", line 86, in predict_datapoint
    raise RuntimeError(error_msg)
RuntimeError: Prediction failed: Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]

Traceback:
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py", line 72, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py", line 30, in predict
    raise customexception(e,sys)

[2025-05-05 12:06:26,317] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 12:06:26] "[31m[1mPOST /predict HTTP/1.1[0m" 400 -
[2025-05-05 12:15:49,304] 97 werkzeug - INFO -  * Detected change in 'C:\\Users\\Praveen\\OneDrive\\Desktop\\weather_prediction\\src\\Weather_prediction\\pipelines\\Prediction_pipeline.py', reloading
